# Notation and Terminology {#notation-and-terminology .unnumbered}

 

## Notation {#notation .unnumbered}
| | |
|:----------------------|:----------------------------------------------------------------------------------------------| 
|  $\mathbb{N}$         | $\{1,2,3,4,\dots\}$ |
| $\mathbb{N}_0$        | $\{0,1,2,3,\dots\}$ |
| $A^c$                 | $\Omega \setminus A$ (note that $\Omega$ is implicit) |
| $A_n \uparrow A$      | $A_{n} \subseteq A_{n+1}$ for all $n$ and $\cup_n A_n = A$ |
| $A_n \downarrow A$    | $A_{n} \supseteq A_{n+1}$ for all $n$ and $\cap_n A_n = A$ |
| $x_n \uparrow x$      | $x_n$ is non-decreasing and $x_n \to x$ |
| $x_n \downarrow x$    | $x_n$ is non-increasing and $x_n \to x$ |
| $\{f<g\}$             | $\{\omega\in\Omega:f(\omega)<g(\omega)\}$ |
| $\sup_n f_n$          | the function $h$ defined by $h(\omega)=\sup_n f_n(\omega)$ for each $\omega$ |
| $\max\{f_1,f_2\}$     | $\sup_{n} f_n$ over $n \in \{1,2\}$ |
| $[x]^+$               | $\max\{0,x\}$, the positive part of $x$ |
| $[x]^-$               | $\max\{0,-x\}$, the negative part of $x$, so $x = [x]^+ - [x]^-$ |
| $\lfloor x \rfloor$   | the largest $n \in \mathbb{Z}$ such that $n \leqslant x \in \mathbb{R}$, or $x$ if $x=\pm\infty$ |
| $\mu$-a.e.            | except on a set $A$ with $\mu(A)=0$ |
| a.e.                  | $\mu$-a.e. when $\mu$ is obvious from the context |
| $\mu$-a.e. $\omega$   | every $\omega \in \Omega \setminus A$, for some set $A\in\mathcal{F}$ with $\mu(A)=0$ |
| $\mathbb{P}$-a.s.     | with probability 1 |
| a.s. on $\omega$      | for $\mathbb{P}$-a.e. $\omega$ |

\clearpage
## Terminology {#terminology .unnumbered}
| | |
|:---------------------|:----------------------------------------------|
| $\sigma$-additivity  | Countable additivity |
| Set                  | a sample space or a subset of a sample space |
| Event                | a measurable subset of a sample space |
| Collection           | a set of subsets of a sample space | 
| Class                | a collection with some structure |
| Family               | a set of classes or functions |

