# Measurable functions and random variables

This chapter intends to introduce and construct the concept of
measurable functions, through a number of important properties and
theorems.

## Definition and properties {#sub:measurable}

As its name suggests, a measurable function between two measurable
spaces preserves the measurability properties of sets.

::: {.definition #measurability name="Measurable function"}
Let $(\Omega_1,\mathcal{F}_1)$ and $(\Omega_2,\mathcal{F}_2)$ be two measurable spaces. A function
$f: \Omega_1 \to \Omega_2$ is called
*$\mathcal{F}_1/\mathcal{F}_2$-measurable* if the pre-image of any
$\mathcal{F}_2$-measurable set is $\mathcal{F}_1$-measurable. That is,
$$f^{-1}(A) \in \mathcal{F}_1, \ \forall A \in \mathcal{F}_2,$$ where
$f^{-1}(A) := \{\omega_1 \in \Omega_1: f(\omega_1) \in A\}$ is the
pre-image of $f$. When the $\sigma$-algebras $\mathcal{F}_1$ and
$\mathcal{F}_2$ are clear from context, we often drop
'$\mathcal{F}_1/\mathcal{F}_2$-measurable' to just 'measurable' or
'$\mathcal{F}_1$-measurable'.
:::

:::{.exmaple}
Let $(\Omega,\mathcal{F})$ be a measurable space and
$A \in \mathcal{F}$. We show that the indicator function
$\dsone_A : \Omega \to \{0,1\}$ given by
\[
\dsone_A(\omega) =
\begin{cases}
1, & \omega \in A\\
0, & \omega \notin A
\end{cases}
\]
is $\mathcal{F}/\mathcal{P}(\{0,1\})$-measurable. Indeed, we have that

-   $\dsone_{A}^{-1}(\emptyset) = \emptyset \in \mathcal{F}$,

-   $\dsone_{A}^{-1}(\{0\}) = A^c \in \mathcal{F}$,

-   $\dsone_{A}^{-1}(\{1\}) = A \in \mathcal{F}$,

-   $\dsone_{A}^{-1}(\{0,1\}) = \dsone_A^{-1}(\{0\}) \cup \dsone_A^{-1}(\{1\}) = A^c \cup A = \Omega \in \mathcal{F}$,

so $\dsone_A$ is indeed measurable.
:::

Naturally, one can expect from
Definition\ \@ref(def:measurability) that a composition of measurable
functions is measurable in any general measurable spaces.

::: {.lemma name="Composition of measurable functions"}
Let $(\Omega_1,\mathcal{F}_1)$, $(\Omega_2,\mathcal{F}_2)$ and
$(\Omega_3,\mathcal{F}_3)$ be measurable spaces and
$f: \Omega_1 \to \Omega_2, \ g: \Omega_2 \to \Omega_3$ be measurable
functions. Then, the composition $g \circ f$ is
($\mathcal{F}_1/\mathcal{F}_3$-)measurable.
:::

::: {.proof}
Since $g$ is measurable, then for any $A \in \mathcal{F}_3$, we
have $g^{-1}(A) \in \mathcal{F}_2$. Now, since $f$ is measurable, then
$f^{-1}(g^{-1}(A)) \in \mathcal{F}_1$. But, this implies that
$$(g \circ f)^{-1}(A) = f^{-1}(g^{-1}(A)) \in \mathcal{F}_1, \ \forall A \in \mathcal{F}_3,$$
so that the composition $g \circ f$ is indeed measurable.
:::

Given a target measurable space $(\Omega_2, \mathcal{F}_2)$ and a
function $f: \Omega_1 \to \Omega_2$, we can construct a $\sigma$-algebra
on $\Omega_1$ induced by $f$.

::: {.definition #salgebrafn}
**($\sigma$-algebra generated by a function $f$)**. Let
$(\Omega_2,\mathcal{F}_2)$ be a measurable space and
$f: \Omega_1 \to \Omega_2$ a function, where $\Omega_1$ is a sample
space. The *$\sigma$-algebra generated by $f$* on $\Omega_1$ is defined
as $$\sigma(f) := \{f^{-1}(A): A \in \mathcal{F}_2\},$$ From
Exercise\ \@ref(exr:pullback), $\sigma(f)$ is indeed a $\sigma$-algebra. See
the diagram below: $$\vcenter{\xymatrix{
  \Omega_1  \ar[d]^{f}  \ar@{.}[r]
               &  \sigma(f)
\\
  \Omega_2  \ar@{.}[r]
               & \mathcal{F}_2  \ar@{->}[u]_{f^{-1}}
}}$$ Note that the notation $\sigma(f)$ does not make explicit its
dependence on $\mathcal{F}_2$.
:::

:::{.remark #salgebrafn}
It follows from the definition of measurability that $\sigma(f)$ is the smallest
$\sigma$-algebra on $\Omega_1$ for which $f$ is measurable. That is, for
any $\sigma$-algebra $\mathcal{G}$ on $\Omega_1$, the function $f$ is
$\mathcal{G}/\mathcal{F}_2$-measurable if and only if
$\mathcal{G}\supseteq \sigma(f)$. The latter condition is interpreted as
$\mathcal{G}$ being *finer* than $\sigma(f)$.
:::

::: {.definition #mupush}
If $f$ is a measurable function from a measure space
$(\Omega_1,\mathcal{F}_1,\mu)$ to $(\Omega_2,\mathcal{F}_2)$, we can
define the *push-forward* measure $f_*\mu$ on $(\Omega_2,\mathcal{F}_2)$
by
$$(f_* \mu)(A) = \mu(\{\omega\in\Omega_1 : f(\omega) \in A\}) = \mu(f^{-1}(A))
.$$ This gives an enlarged diagram as follows: 
$$
\vcenter{\xymatrix{
  \Omega_1  \ar[d]^{f}  \ar@{.}[r]
               &  \sigma(f)  \ar@{.}[r]
                           &  \mu  \ar[d]^{\circ f^{-1}}
\\
  \Omega_2  \ar@{.}[r]
               & \mathcal{F}_2  \ar@{->}[u]_{f^{-1}}  \ar@{.}[r]
                           &  f_* \mu
}}
$$
:::

Quite often, it is unhandy to check measurability using the whole target
space, in which case the following lemma comes in our aid.

::: {.lemma #meascriterion name="Measurability criterion"}
Let $(\Omega_1,\mathcal{F}_1)$ and $(\Omega_2,\mathcal{F}_2)$ be measurable spaces. Suppose
$\mathcal{F}_2=\sigma(\mathcal{E})$ for some class $\mathcal{E}$ of
subsets of $\Omega_2$. Then, $f: \Omega_1 \to \Omega_2$ is a measurable
function, if and only if $f^{-1}(A) \in \mathcal{F}_1$ for all
$A \in \mathcal{E}$.
:::

::: {.proof}
The first direction follows from Definition\ \@ref(def:measurability). Since any $A \in \mathcal{E}$ implies that $A \in \mathcal{F}_2$, then measurability of $f$ gives
$f^{-1}(A) \in \mathcal{F}_1$. Conversely, suppose that
$f^{-1}(A) \in \mathcal{F}_1$, for each $A \in \mathcal{E}$. To prove
that $f$ is measurable, it suffices to show that the collection
$\mathcal{G}$ given by
$$\mathcal{G} = \{A \subseteq \Omega_2: f^{-1}(A) \in \mathcal{F}_1\}$$
is a $\sigma$-algebra on $\Omega_2$, where
$\mathcal{E} \subset \mathcal{G}$, so that
$\mathcal{F}_2 = \sigma(\mathcal{E}) \subseteq \mathcal{G}$. Indeed, we
observe that

(i) First, $\Omega_2 \in \mathcal{G}$, since
    $f^{-1}(\Omega_2) = \Omega_1 \in \mathcal{F}_1$.

(ii) Let $A \in \mathcal{G}$, so $f^{-1}(A) \in \mathcal{F}_1$. Since
     $f$ has domain $\Omega_1$ and codomain $\Omega_2$, we have
     $f^{-1}(\Omega_2 \setminus A) = \Omega_1 \setminus f^{-1}(A)$.
     Since $\mathcal{F}_1$ is closed under complements, we have
     $\Omega_1 \setminus f^{-1}(A) \in \mathcal{F}_1$, hence
     $A^c \in \mathcal{G}$.

(iii) Let $A_1, A_2, \dots \in \mathcal{G}$. Then,
      $f^{-1}(A_k) \in \mathcal{F}_1$, for each $k \in \mathbb{N}$. This
      in turn implies that
      $f^{-1}(\bigcup_{i=1}^{\infty}A_i) = \bigcup_{i=1}^{\infty}f^{-1}(A_i) \in \mathcal{F}_1$.
      Thus, $\bigcup_{i=1}^{\infty}A_i \in \mathcal{G}$.

and so $\mathcal{G}$ defines a $\sigma$-algebra on $\Omega_2$.
:::

::: {.lemma name="Continuous functions"}
Let $\Omega_1$ and $\Omega_2$ be metric spaces. Take $\mathcal{B}_1$ and $\mathcal{B}_2$, respectively,
as the Borel $\sigma$-algebras, that is, those generated by the families
of open sets. If $f:\Omega_1\to\Omega_2$ is continuous, then it is
measurable.
:::

::: {.proof}
Denote by $\mathcal{O}$ the class of open sets in $\Omega_2$.
Let $B \in \mathcal{O}$. Since $f$ is continuous, $f^{-1}(B)$ is an open
set in $\Omega_1$, hence $f^{-1}(B) \in \mathcal{B}_1$. Since
$\mathcal{B}_2 = \sigma(\mathcal{O})$, by
Lemma\ \@ref(lem:meascriterion), $f$ is measurable.
:::

## Extended Borel functions and random variables

We now discuss extended Borel functions and extended random variables.

### Extended Borel functions

::: {.definition #borelfn name="Extended Borel function"}
Let $(\Omega,\mathcal{F})$ be a measurable space. If
$f: (\Omega,\mathcal{F}) \to (\mathbb{R},\mathcal{B})$ is a measurable
function, then it is called a *Borel function*. Likewise, a measurable
function taking values on $(\overline{\mathbb{R}},\mathcal{B})$ is
called an *extended Borel function*.
:::

One can think of a Borel function as simply an extended Borel function
that never takes infinite values. So properties of extended Borel
functions also hold for Borel functions.

Recall from ยง\@ref(sub:borelreal) the several classes of subsets of
$\mathbb{R}$ that generate $\mathcal{B}(\mathbb{R})$ and hence
$\mathcal{B}(\overline{\mathbb{R}})$. We can then apply
Lemma\ \@ref(lem:meascriterion) above to conclude that measurability
suffices to hold for each such class on $\overline{\mathbb{R}}$.

::: {.lemma #borelcriteria name="Equivalent criteria"}
Let $(\Omega,\mathcal{F})$ be a measurable space and $f: \Omega \to \overline{\mathbb{R}}$. The
following are equivalent:

1.  $f$ is an extended Borel function,

2.  $\{f < a\} \in \mathcal{F}, \ \forall a \in \mathbb{R}$,

3.  $\{f \leqslant a\} \in \mathcal{F}, \ \forall a \in \mathbb{R}$,

4.  $\{f > a\} \in \mathcal{F}, \ \forall a \in \mathbb{R}$,

5.  $\{f \geqslant a\} \in \mathcal{F}, \ \forall a \in \mathbb{R}$.
:::

::: {.proof}
By Exercise\ \@ref(exr:generateextborel), each one of the classes
$\{f < a\}_{a\in\mathbb{R}}$, $\{f \leqslant a\}_{a\in\mathbb{R}}$,
$\{f > a\}_{a\in\mathbb{R}}$ and $\{f \geqslant a\}_{a\in\mathbb{R}}$
generates $\mathcal{B}(\overline{\mathbb{R}})$. Hence, the equivalence
follows from Lemma\ \@ref(lem:meascriterion).
:::

::: {.lemma #salgebracriterion name="Pull-back of Borel sets"}
Let $\Omega$ be a sample space and $f$ a function from $\Omega$ to
$(\overline{\mathbb{R}},\mathcal{B})$. Then,
$\sigma(f) = \sigma(\{\{f \leqslant a\}: a \in \mathbb{R}\}).$
:::

::: {.proof}
Since $[-\infty,a]\in\mathcal{B}$, we have
$\{f \leqslant a\} \in \sigma(f)$, for each $a \in \mathbb{R}$. Thus,
$\{f \leqslant a\}_{a\in\mathbb{R}} \subseteq \sigma(f)$, and so
$\mathcal{G}:= \sigma( \{f \leqslant a\}_{a\in\mathbb{R}} ) \subseteq \sigma(\sigma(f)) = \sigma(f)$.
On the other hand, by
Lemma\ \@ref(lem:borelcriteria) $f$ is $\mathcal{G}/\mathcal{B}(\overline{\mathbb{R}})$-measurable. Therefore,
by the remark following Definition\ \@ref(def:salgebrafn), $\mathcal{G}\supseteq \sigma(f)$.
:::

:::{.example #simplemeasurable}
Let $(\Omega,\mathcal{F})$ be a measurable
space. Given a partition $A_1, \dots, A_n \in \mathcal{F}$ of $\Omega$
and $b_1, \dots, b_n \in \mathbb{R}$, define the function
$f: \Omega \to \mathbb{R}$ by
$$f(\omega) := b_1 \dsone_{A_1}(\omega) + \dots + b_n \dsone_{A_n}(\omega), \ \omega \in \Omega.$$
Suppose that $A_i \cap A_j = \emptyset$ for $i \neq j$, and
$b_i \neq b_j$ for $i \neq j$. We will show that
$\sigma(f) = \sigma(\{A_1, \dots, A_n\})$. To prove that
$\sigma(f) \subseteq \sigma(\{A_1, \dots, A_n\})$, it suffices to show
that
$$\{f \leqslant a\} \in \sigma(\{A_1,\dots,A_n\}), \ \forall a \in \mathbb{R},$$
and by Lemma\ \@ref(lem:salgebracriterion), we can conclude that
$\sigma(f) \subseteq \sigma(\{A_1, \dots, A_n\})$. Now note that
$$\begin{aligned}
\nonumber
\{f \leqslant a\} &= \{b_1 \dsone_{A_1} + \dots + b_n \dsone_{A_n} \leqslant a\} \\
&= \left\{A_{i_j}: b_{i_j} \leqslant a, \ i_j \in \{1,\dots,n\}, \ j = 1,\dots,m\right\} \\
&= \bigcup_{j=1}^{m}A_{i_{j}} \in \sigma(\{A_1,\dots,A_n\}),\end{aligned}$$
which follows by construction of $f$. Conversely, to show that
$\{A_1, \dots, A_n\} \subset \sigma(f)$, observe that
$$\{f = b_i\} = A_i \in \sigma(f), \ i = 1, \dots, n,$$ and so
$\sigma(\{A_1, \dots, A_n\}) \subseteq \sigma(f)$.
:::

:::{.exercise #coarser}
Consider the measurable space $([0,1], \mathcal{B}([0,1]))$, define the functions
$f,g: [0,1] \to \{0,1,2,3\}$ by

\begin{equation}
\nonumber
f(\omega) =
\begin{cases}
1, & \omega \in [0, \frac{1}{4}]\\
2, & \omega \in (\frac{1}{4}, \frac{1}{2}]\\
3, & \omega \in (\frac{1}{2},1]
\end{cases}
, \ g(\omega) =
\begin{cases}
0, & \omega \in [0,\frac{1}{2}]\\
1, & \omega \in (\frac{1}{2},1]
\end{cases}
\end{equation}

Find $\sigma(f)$, and check that $\sigma(g) \subset \sigma(f)$.
:::

### Extended random variables

::: {.definition name="Extended random variable"}
An extended Borel function
$X$ on a probability space $(\Omega,\mathcal{F},\mathbb{P})$ is called
an *extended random variable*. The *distribution of $X$* is the
push-forward measure $\mathbb{P}_X$ on
$(\overline{\mathbb{R}},\mathcal{B})$ given by
$$\mathbb{P}_X := X_* \mathbb{P}= \mathbb{P}\circ X^{-1} ,$$ that is,
$$\mathbb{P}_X(A) = \mathbb{P}(X \in A) = \mathbb{P}(\{\omega:X(\omega)\in A\}), \ \ A \in \mathcal{B}(\overline{\mathbb{R}}).$$
The function $F_X:\overline{\mathbb{R}}\to[0,1]$ given by
$$F_X(x) := \mathbb{P}_X \big( [-\infty, x] \big)$$ is called *the
cumulative distribution function of $X$*.
:::

:::{.remark #cumulebsti}
If $X$ never take values $\pm\infty$, we say that $X$ is a *random
variable*.
:::

:::{.remark}
For a random variable $X$, the measure $\mathbb{P}_X$ on
$(\mathbb{R},\mathcal{B})$ is the Lebesgue-Stieltjes measure induced by
the function $F_X$, as defined in ยง\@ref(sub:lebstiel).
:::

:::{.example}
Let $(\Omega,\mathcal{F},\mathbb{P})$ be a probability space and $A$
some event in $\mathcal{F}$. Consider the random variable $X$ given by
$$X(\omega) = \dsone_{A}(\omega), \ \omega \in \Omega,$$ with
distribution $$\mathbb{P}(X = 1) = \mathbb{P}(A) =: p \in [0,1].$$ Then,
$X$ is called a *Bernoulli random variable with parameter $p$*.
:::

:::{.example}
Let us revisit the construction of Example\ \@ref(exm:simplemeasurable). Let $(\Omega,\mathcal{F},\mathbb{P})$
be a probability space, and for $n \in \mathbb{N}$, let
$A_1, \dots, A_n$ be events in $\mathcal{F}$ that partition $\Omega$ and
$b_1, \dots, b_n$ distinct real numbers. Consider the random variable
$X$ defined by
$$X(\omega) = \sum_{i=1}^{n}b_i\dsone_{A_i}(\omega), \ \omega \in \Omega,$$
with distribution
$$\mathbb{P}(X = b_k) = \mathbb{P}(A_k) =: p_k \in [0,1], \ k = 1, \dots, n.$$
Then, $X$ is called a *simple random variable that takes value $b_k$
with probability $p_k$*, and has cumulative distribution function
$$F_X(x) = \sum_{i=1}^{n}p_i \dsone_{\{(-\infty,x]\}}(b_i).
\qedhere$$
:::

:::{.example}
Take $\Omega=\mathbb{R}$, $\mathcal{F}=\mathcal{B}$ and let
$\mathbb{P}=m_{|_{[0,1]}}$ be the restriction of the Lebesgue measure to
$[0,1]$. Let $X(\omega)= - \log |\omega|$. Then $X$ is measurable
(why?), hence an extended random variable. Moreover, $$F_X(x) =
m(\{\omega:-\log|\omega| \leqslant x\}\cap[0,1]))
=
\begin{cases}
1 - e^{-x}, & x \geqslant 0,
\\
0, & x \leqslant 0,
\end{cases}$$ and $X$ is said to follow the *exponential distribution*
with unit parameter.
:::

## Operations on extended Borel functions {#sub:operations}

Given a measurable space $(\Omega, \mathcal{F})$, let
$f,g : \Omega \to \overline{\mathbb{R}}$ be extended Borel functions. A
property that we constantly use is that measurability is preserved under
various operations. The properties studied in this section are so basic
that in subsequent chapters we use them without making explicit
reference.

::: {.lemma #comparison name="Comparison of functions"}
Let $(\Omega,\mathcal{F})$ be a
measurable space and $f,g: \Omega \to \overline{\mathbb{R}}$ be extended
Borel functions. Then, the subsets of $\Omega$ given by $\{f < g\}$,
$\{f \leqslant g\}$, $\{f=g\}$, and $\{f \neq g\}$ are in
$\mathcal{F}$.
:::

::: {.proof}
Since $\mathbb{Q}$ is dense in $\mathbb{R}$, for each $\omega\in\Omega$, $f(\omega) < g(\omega)$ if and only if there is
$r \in \mathbb{Q}$ such that $f(\omega) < r < g(\omega)$. Thus, we can
express $\{\omega: f(\omega) < g(\omega)\}$ as the union of
$\{\omega: f(\omega) < r < g(\omega)\}$ over all $r \in \mathbb{Q}$, and
$\mathbb{Q}$ is countable. Further, $\{f<r\},\{r<g\} \in \mathcal{F}$,
by Lemma\ \@ref(lem:borelcriteria) 3 and 4. Putting everything together yields
$$\{f < g\} =
%\{\omega: f(\omega) < g(\omega)\} =
\bigcup_{r\in\mathbb{Q}}(\{f < r < g\}) = \bigcup_{r\in\mathbb{Q}}(\{f<r\}\cap\{r<g\}) \in \mathcal{F}.$$
Now, we can see that $$\begin{aligned}
&\{f \neq g\} = \{f < g\} \cup \{f > g\} \in \mathcal{F}, \\
&\{f = g\} = \{f \neq g\}^c \in \mathcal{F}, \\
&\{f \leqslant g\} = \{f < g\} \cup \{f = g\} \in \mathcal{F}.\end{aligned}$$
This proves the lemma.
:::

As one would expect, sums and products of Borel functions $f$ and $g$ on
some measurable space $(\Omega, \mathcal{F})$ are also Borel.
Importantly, we can extend this to $f$ and $g$ being extended Borel
functions, as we only need to impose restrictions on infinite values. In
particular, $f + g$ is extended Borel if it is well-defined, that is, if
there is no $\omega \in \Omega$ for which
$f(\omega) + g(\omega) = \infty - \infty$.

::: {.lemma #boreloperations01 name="Sums and products"}
Let $(\Omega,\mathcal{F})$ be a
measurable space and $f,g: \Omega \to \mathbb{R}$ be extended Borel
functions. Then $fg$ is an extended Borel function. If $f + g$ is
well-defined for all $\omega$, then it is an extended Borel function.
:::

::: {.proof}
First, we show that $af + b$ is an extended Borel function for
every $a, b \in \mathbb{R}$. For $a = 0$, the proof is trivial, so we
assume that $a \in \overline{\mathbb{R}}\setminus \{0\}$. We have that
$$\{af+b < c\} = \{af < c-b\} =
\begin{cases}
\{f < \frac{c-b}{a}\}, & a > 0 \\
\{f > \frac{c-b}{a}\}, & a < 0
\end{cases}$$ where
$\{f < \frac{c-b}{a}\}, \{f > \frac{c-b}{a}\} \in \mathcal{F}$, by
Lemma\ \@ref(lem:borelcriteria) 3 and 4.

Now suppose $f + g$ is well-defined for all $\omega$. For every
$b \in \mathbb{R}$, it follows that $$\begin{aligned}
&\{f + g < b\} = \{f < b - g\} \in \mathcal{F},\end{aligned}$$ since
$b - g$ is extended Borel and by applying
Lemma\ \@ref(lem:comparison)
Next, we show that $fg$ is extended Borel, where we treat the case of
infinite values separately. First we show that $f^2$ is also extended
Borel. We have that $$\{f^2 > a\} =
\begin{cases}
\Omega, & a < 0\\
\{f < -\sqrt{a}\} \cup \{f > \sqrt{a}\}, & a \geqslant 0
\end{cases}$$ where $\Omega \in \mathcal{F}$ and
$\{f < -\sqrt{a}\} \cup \{f > \sqrt{a}\} \in \mathcal{F}$, by
Lemma\ \@ref(lem:borelcriteria) 3. and 4..

Now suppose $f$ and $g$ are both finite Borel functions. Notice that we
can write $$fg = \frac{1}{4}[(f+g)^2 - (f-g)^2],$$ where $(f+g)^2$ and
$(f-g)^2$ are both Borel, since $f+g$ and $f-g$ are, so we can conclude
that $fg$ is Borel.

Finally, suppose $f$ and $g$ are both extended Borel functions. Let
$A = \{\omega : f(\omega) \in \mathbb{R}, g(\omega) \in \mathbb{R}\}$,
and
$B = A^c = \{\omega : f(\omega)=\pm \infty \text{ or } g(\omega)=\pm \infty \}$.
Note that $A,B \in \mathcal{F}$. Define $f_1 = f \dsone_A$,
$f_2 = f \dsone_B$, $g_1 = g \dsone_A$, $g_2 = g \dsone_B$.
Then $f_2 g_2$ is measurable (why?), and by the previous case $f_1 g_1$
is measurable. Since $fg = f_1g_1 + f_2g_2$, we conclude that $fg$ is
measurable.
:::

:::{.exercise #afmeas}
If $f$ is an extended Borel function on some measurable space $(\Omega, \mathcal{F})$, then any scalar multiple of $f$ is also extended Borel, that is for any
$a \in \overline{\mathbb{R}}$, $af$ is an extended Borel function.
::::

::: {.lemma #borelmaxmin name="Maximum and minimum"}
Let $(\Omega,\mathcal{F})$ be a measurable space and $f,g: \Omega \to \overline{\mathbb{R}}$ be extended
Borel functions. Then, we have that $\max\{f,g\}$ and $\min\{f,g\}$ are
extended Borel functions.
:::

::: {.proof}
By taking the suitable inequalities for minimum and maximum,
For every $a \in \mathbb{R}$, we have $$\begin{aligned}
%&\{\min\{f,g\} > a\} = \{f > a\} \cap \{g > a\} \in \mathcal{F}, \\
&\{\max\{f,g\} < a\} = \{f < a\} \cap \{g < a\} \in \mathcal{F},\end{aligned}$$
since $\{f<a\},\{g<a\} \in \mathcal{F}$ by
Lemma\ \@ref(lem:borelcriteria) 3. 
Finally, use $\min\{f,g\} = -\max\{-f,-g\}$
and Exercise\ \@ref(exr:afmeas) for the minimum.
:::

Limiting operations also maintain measurability.

::: {.lemma #boreloperations02 name="Suprema and limits of functions"}
Let $(\Omega,\mathcal{F})$ be a measurable space and $(f_n)_{n\geqslant 1}$
be a sequence of extended Borel functions. Then, the functions
$\sup_{n \geqslant 1}f_n$, $\inf_{n\geqslant 1}f_n$,
$\limsup_{n\to\infty}f_n$, $\liminf_{n\to\infty}f_n$ are extended Borel
functions. Moreover, if $\lim_{n\to\infty}f_n$ exists, then
$$\lim_{n\to\infty}f_n = \limsup\limits_{n\to\infty}f_n = \liminf\limits_{n\to\infty}f_n,$$
is an extended Borel function.
:::

::: {.proof}
To prove that $\sup_{n \geqslant 1}f_n$ is extended Borel, the
idea is similar to the proof of
Lemma\ \@ref(lem:borelmaxmin). For any $a \in \mathbb{R}$, we can write
$$\left\{\sup\limits_{n \geqslant 1}f_n \leqslant a\right\} = \bigcap_{n=1}^{\infty}\{f_n \leqslant a\} \in \mathcal{F}.$$
where we used the fact that $\mathcal{F}$ is a $\sigma$-algebra, so it
closed under countable intersections. The claim for
$\inf_{n \geqslant 1}f_n$ follows by noticing that
$$\inf\limits_{n \geqslant 1} f_n = - \sup\limits_{n \geqslant 1} (- f_n),$$
and using Exercise\ \@ref(exr:afmeas). Now, using the definition of limit superior
and
limit inferior, $$\begin{aligned}
\limsup\limits_{n\to\infty}f_n
&=
\inf_{n \geqslant 1} \sup_{m \geqslant n}f_m,
\\
\liminf\limits_{n\to\infty}f_n
&=\sup_{n \geqslant 1} \inf_{m \geqslant n}f_m,\end{aligned}$$
which both are extended Borel, by applying the above properties twice
for each limit. Finally, assuming that the limit of $f_n$ exists, we
have $\lim_{n\to\infty}f_n = \limsup_{n\to\infty}f_n$, which concludes
the proof.
:::
