# Postponed proofs

:::{.lemma #algebrasigma}
An algebra closed under countable disjoint unions is a
$\sigma$-algebra.
:::

:::{.proof}
Exercise.
:::

:::{.proof name="Proof of Theorem \@ref(thm:dynkin)"}
We define $\mathcal{G}$ as the smallest
$\lambda$-system[^18] that contains the $\pi$-system $\mathcal{C}$, and
show that $\mathcal{G}$ is also a $\pi$ system. By
Lemma \@ref(lem:algebrasigma), $\mathcal{G}$ is a
$\sigma$-algebra, hence
$\mathcal{C}\subseteq\sigma(\mathcal{C})\subseteq\mathcal{G}\subseteq\mathcal{D}$,
proving the theorem.

The key idea is to consider, for each $B\in\mathcal{G}$, the collection
$$\nonumber
\mathcal{F}_{B}:=\{A\in\mathcal{G}:A\cap B\in\mathcal{G}\}.$$

We can see that $\mathcal{F}_{B}$ is a $\lambda$-system using
$A^{c}\cap B=((A\cap B)\cup B^{c})^{c}$.

Now, let $B\in\mathcal{C}$. Since $\mathcal{C}$ is a $\pi$-system,
$\mathcal{C}\subseteq\mathcal{F}_{B}$. But $\mathcal{G}$ is the smallest
$\lambda$-system that contains $\mathcal{C}$, so
$\mathcal{F}_{B}=\mathcal{G}$.

Finally, let $D\in\mathcal{G}$. For every $B\in\mathcal{C}$, we have
$D\in\mathcal{F}_{B}$, which is equivalent to $B\in\mathcal{F}_{D}$.
Hence, $\mathcal{C}\subseteq\mathcal{F}_{D}$. But $\mathcal{G}$ is the
smallest $\lambda$-system that contains $\mathcal{C}$, so
$\mathcal{F}_{D}=\mathcal{G}$. Since this is true for every
$D\in\mathcal{G}$, we conclude that $\mathcal{G}$ is a $\pi$-system,
which completes the proof.[^19]
:::

:::{.proof name="Proof of Lemma \@ref(lem:outer)"}
That $\mu^{*}(E)\leqslant\mu^{*}(F)$ when
$E\subseteq F$ follows from $\mathcal{C}_{F}\subseteq\mathcal{C}_{E}$.

We now prove that
$\mu^{*}(\cup_{n}E_{n})\leqslant\sum_{n}\mu^{*}(E_{n})$. Let
$\varepsilon>0$, for each $n\in\mathbb{N}$, by definition of
$\mu^{*}(E_{n})$ we can take $(A_{n,k})_{k}$ in $\mathcal{A}$ such that
$E_{n}\subseteq\cup_{k}A_{n,k}$ and
$\sum_{k}\mu(A_{n,k})\leqslant\mu^{*}(E_{n})+\varepsilon2^{-n}$. Since
$\cup_{n}E_{n}\subseteq\cup_{n,k}A_{n,k}$, by definition of
$\mu^{*}(\cup_{n}E_{n})$ we have
$\mu^{*}(\cup_{n}E_{n})\leqslant\sum_{n,k}\mu(A_{n,k})=\sum_{n}\sum_{k}\mu(A_{n,k})\leqslant\sum_{n}\mu^{*}(E_{n})+\varepsilon2^{-n}=\sum_{n}\mu^{*}(E_{n})+\varepsilon$.
Since $\varepsilon$ is arbitrary, the inequality follows.

We finally prove that $\mu^{*}(A)=\mu(A)$ for $A\in\mathcal{A}$. That
$\mu^{*}(A)\leqslant\mu(A)$ follows immediately by taking
$(A,\emptyset,\emptyset,\emptyset\dots)\in\mathcal{C}_{A}$. We show that
$\mu^{*}(A)\geqslant\mu(A)$ using the assumption that $\mu$ is
$\sigma$-additive on $\mathcal{A}$. Let $(A_{n})_{n}\in\mathcal{C}_{A}$.
Take $B_{n}=A\cap A_{n}\cap(\cap_{k=1}^{n-1}A_{k}^{c})$, so they form a
partition of $A$. Hence,
$\mu(A)=\sum_{n}\mu(B_{n})\leqslant\sum_{n}\mu(A_{n})$. Since this holds
for any $(A_{n})_{n}\in\mathcal{C}_{A}$, we have
$\mu(A)\leqslant\mu^{*}(A)$, concluding the proof.[^20]
:::

:::{.proof name="Proof of Lemma \@ref(lem:caratheodory)"}
We make extensive use of Lemma \@ref(lem:outer). Let $\mathcal{F}= \mathcal{F}^*$.

We first prove that $\mathcal{A}\subseteq\mathcal{F}$. Let
$A\in\mathcal{A}$ and $E\subseteq\Omega$. For $\varepsilon>0$, by
definition of $\mu^{*}$ there are $A_{1},A_{2},\cdots\in\mathcal{A}$
with $E\subseteq\cup_{n}A_{n}$ and
$\sum_{n}\mu(A_{n})\leqslant\mu^{*}(E)+\varepsilon$. Then
$$\begin{gathered}
\nonumber
\mu^{*}(E)\leqslant\mu^{*}(E\cap A)+\mu^{*}(E\cap A^{c})\leqslant\sum_{n}\mu^{*}(A_{n}\cap A)+\sum_{n}\mu^{*}(A_{n}\cap A^{c})=\\
=\sum_{n}\mu(A_{n}\cap A)+\sum_{n}\mu(A_{n}\cap A^{c})=\sum_{n}\mu(A_{n})\leqslant\mu^{*}(E)+\varepsilon.\end{gathered}$$
We used sub-additivity of $\mu^{*}$ twice, the fact that $\mu^{*}=\mu$
on $\mathcal{A}$, and finite additivity of $\mu$. Since $\varepsilon$ is
arbitrary, we have $A\in\mathcal{F}$. Hence,
$\mathcal{A}\subseteq\mathcal{F}$.

We now prove that $\mathcal{F}$ is a $\sigma$-algebra and
$\mu^{*}$ is $\sigma$-additive on $\mathcal{F}$.

*Step 1.* The class $\mathcal{F}$ is an algebra.

Trivially, $\Omega\in\mathcal{F}$ and $A^{c}\in\mathcal{F}$ for all
$A\in\mathcal{F}$. Now for $A,B\in\mathcal{F}$, using sub-additivity we
get
$\mu^{*}(E)\leqslant\mu^{*}(E\cap(A\cap B))+\mu^{*}(A\cap(A\cap B)^{c})\leqslant\mu^{*}(E\cap A\cap B)+\mu(E\cap A\cap B^{c})+\mu^{*}(E\cap A^{c}\cap B)+\mu^{*}(E\cap A^{c}\cap B^{c})=\mu^{*}(E\cap A)+\mu^{*}(E\cap A^{c})=\mu^{*}(E),$
so $A\cap B\in\mathcal{F}$. Hence, $\mathcal{F}$ is an algebra.

*Step 2.* For disjoint $A_{1},\dots,A_{n}\in\mathcal{F}$, $$\nonumber
\mu^{*}\big(E\cap(\cup_{k=1}^{n}A_{k})\big)=\sum_{k=1}^{n}\mu^{*}(E\cap A_{k}).$$

Using that $A_{1}\in\mathcal{F}$ and
$A_{1}\cap(\cup_{k=2}^{n}A_{k})=\emptyset,$ we get
$\mu^{*}\big(E\cap(\cup_{k=1}^{n}A_{k})\big)=\mu^{*}\big(E\cap A_{1}\big)+\mu^{*}\big(E\cap(\cup_{k=2}^{n}A_{k})\big)$.
Using the same for $A_{2}$, then $A_{3}$, and so on, we get the above
identity.

*Step 3.* For $A_{1},A_{2},\cdots\in\mathcal{F}$ disjoint,
$\cup_{n}A_{n}\in\mathcal{F}$ and
$\mu^{*}(\cup_{n}A_{n})=\sum_{n}\mu^{*}(A_{n})$.

These are both proved by showing $$\nonumber
\mu^{*}(E)\leqslant\mu^{*}(E\cap G)+\mu^{*}(E\cap G^{c})\leqslant\sum_{k=1}^{\infty}\mu^{*}(E\cap A_{k})+\mu^{*}(E\cap G^{c})\leqslant\mu^{*}(E),$$
where $G=\cup_{n}A_{n}$. The above chain readily implies that
$\cup_{n}A_{n}\in\mathcal{F}$, and
$\mu^{*}(\cup_{n}A_{n})=\sum_{n}\mu^{*}(A_{n})$ follows by taking
$E=\cup_{n}A_{n}$. The first two inequalities are sub-additivity. For
the third inequality, writing $G_{n}:=\cup_{k=1}^{n}A_{k}$, we have
$\mu^{*}(E)=\mu^{*}(E\cap G_{n})+\mu^{*}(E\cap G_{n}^{c})=\sum_{k=1}^{n}\mu^{*}(E\cap A_{k})+\mu^{*}(E\cap G_{n}^{c})\geqslant\sum_{k=1}^{n}\mu^{*}(E\cap A_{k})+\mu^{*}(E\cap G^{c})\to\sum_{k=1}^{\infty}\mu^{*}(E\cap A_{k})+\mu^{*}(E\cap G^{c}),$
where the first equality holds since $G_{n}\in\mathcal{F}$ by Step 1,
and and second equality follows from Step 2.

By Lemma \@ref(lem:algebrasigma), this concludes the proof.[^21]
:::

:::{.proof name="Proof of Lemma \@ref(lem:premeasure)"}
It is enough to show that, if
$A_{n}\downarrow\emptyset$ in $\mathcal{A}$, then $m(A_{n})\to0$ (why?).
Let $A_{n}$ be a decreasing sequence with
$m(A_{n})\geqslant 2\varepsilon$ for all $n$. It is enough to prove that
$\cap_{n}A_{n}\ne\emptyset$ (why?). For each $k\in\mathbb{N}$, we can
find $B_{k}\in\mathcal{A}$ such that $\overline{B_{k}}\subseteq A_{k}$
and $m(A_{k}\setminus B_{k})\leqslant\varepsilon2^{-k}$ (just make the
intervals of $A_{k}$ slightly shorter on the left). Then for each $n$,
$m(\cup_{k=1}^{n}(A_{k}\setminus B_{k})\leqslant\varepsilon$ by
additivity of $m$ on $\mathcal{A}$. On the other hand,
$A_{n}\setminus\cap_{k=1}^{n}B_{k}=\cup_{k=1}^{n}A_{n}\setminus B_{k}\subseteq\cup_{k=1}^{n}A_{k}\setminus B_{k}$,
so $m(A_{n}\setminus\cap_{k=1}^{n}B_{k})\leqslant\varepsilon$, and since
$m(A_{n})\geqslant 2\varepsilon$, we have
$m(\cap_{k=1}^{n}B_{k})\geqslant\varepsilon$. In particular,
$K_{n}:=\cap_{k=1}^{n}\overline{B_{k}}\ne\emptyset$. Since $K_{n}$ are
compact sets by Heine-Borel Theorem,
$\cap_{n=1}^{\infty}K_{n}\neq\emptyset$. Hence,
$\emptyset\ne\cap_{n=1}^{\infty}K_{n}=\cap_{n=1}^{\infty}\overline{B_{n}}\subseteq\cap_{n=1}^{\infty}A_{n}$,
concluding the proof.[^22]
:::

We now move on to the proof of the Radon-Nikodým Theorem.

A *signed measure* on $(\Omega,\mathcal{F})$ is a function
$\mu:\mathcal{F}\to\mathbb{R}$ such that $\mu(\emptyset)=0$ and, for
disjoint $(A_{n})_{n}$ in $\mathcal{F}$,
$\mu(\cup_{n}A_{n})=\sum_{n}\mu(A_{n})$. We say that $N$ is a *negative
set* for $\mu$ if $\mu(A\cap N)\leqslant 0$ for every $A\in\mathcal{F}$.

:::{.lemma}
Let $\mu$ be a signed measure on $(\Omega,\mathcal{F})$.
For every $D\in\mathcal{F}$, there exits $A\in\mathcal{F}$ such that $A$
is negative, $A\subseteq D$, and $\mu(A)\leqslant\mu(D)$.
:::

:::{.proof}
We are going to define a decreasing sequence $(A_{n})_{n}$ such
that $A_{n}\downarrow A$. Start defining $A_{0}:=D$. If $A_{n}$ has been
defined, let $t_{n}:=\sup\{\mu(B):B\in\mathcal{F},B\subseteq A_{n}\}$.
Note that $t_{n}\geqslant\mu(\emptyset)=0$. Let
$\delta_{n}:=\min\{\frac{t_{n}}{2},1\}$ (we only need the min to ensure
that $0\leqslant\delta_{n}<t_{n}$ when $0<t_{n}\leqslant+\infty$). Take
$B_{n}\in\mathcal{F}$ such that $B_{n}\subseteq A_{n}$ and
$\mu(B_{n})\geqslant\delta_{n}$ and define
$A_{n+1}:=A_{n}\setminus B_{n}$. Then
$\mu(A)=\mu(D\setminus\cup_{n}B_{n})=\mu(D)-\sum_{n}\mu(B_{n})\leqslant\mu(D)$.
On the other hand, $\sum_{n}\mu(B_{n})=\mu(B)<\infty$, so
$\mu(B_{n})\to0$ as $n\to\infty$, hence $t_{n}\to0$. In particular, for
every $B\in\mathcal{F}$ such that $B\subseteq A$, for every
$n\in\mathbb{N}$, we have $B\subseteq A_{n}$ which means
$\mu(B)\leqslant t_{n}$, so $\mu(B)\leqslant 0$, which means that $A$ is
a negative set.[^23]
:::

::: {.theorem name="Hahn Decomposition Theorem"}
Let $\mu$ be a signed
measure on $(\Omega,\mathcal{F})$. Then there is $N\in\mathcal{F}$ such
that for every $B\in\mathcal{F}$, $\mu(B\cap N)\leqslant 0$ and
$\mu(B\cap N^{c})\geqslant 0$.
:::

::: {.proof}
Let $\alpha:=\inf\{\mu(A):A\in\mathcal{F}\text{ is a negative set for }\mu\}$,
and note that $\alpha\leqslant\mu(\emptyset)=0$. Take $A_{n}$ such that
$\mu(A_{n})\to\alpha$, and let $N:=\cup_{n}A_{n}$. Now, a countable
union of negative sets is negative (why?), so $N$ is a negative set.

It remains to show that $\mu(B) \geqslant 0$ for measurable
$B \subseteq N^c$. First,
$\alpha\leqslant\mu(N)=\mu(A_{n})+\mu(N\setminus A_{n})\leqslant\mu(A_{n})\to\alpha$,
so $\alpha=\mu(N)\ne-\infty$. Now suppose $B\in\mathcal{F}$ and
$B\subseteq N^{c}$. By the previous lemma, there exists
$A\in\mathcal{F}$ such that $A\subseteq B$, $A$ is negative and
$\mu(A)\leqslant\mu(B)$. On the other hand,
$\alpha\leqslant\mu(A\cup N)=\mu(A)+\mu(N)=\mu(A)+\alpha$, so
$\mu(B)\geqslant\mu(A)\geqslant 0$, completing the proof.
:::

:::{.proof name="Proof of Theorem \@ref(thm:radonnikodym)"}
We split the proof into 3 main steps.

*Step 1.* We can assume that $\mu$ and $\nu$ are finite.

Indeed, suppose we had proved the theorem for finite measures. Since
$\mu$ and $\nu$ are $\sigma$-finite, there is a measurable
partition $(A_{n})_{n\in\mathbb{N}}$ of $\Omega$ such that
$\mu_{n}:=\mu_{|_{A_{n}}}$ and $\nu_{n}:=\nu_{|_{A_{n}}}$ are finite and
$\nu_{n}\ll\mu_{n}$. Take the corresponding
$f_{n}=\frac{\mathrm{d}\nu_{n}}{\mathrm{d}\mu_{n}}$, and define
$f=\sum_{n}f_{n}\dsone_{A_{n}}$. Checking that
$f=\frac{\mathrm{d}\nu}{\mathrm{d}\mu}$ is straightforward:
$$\nu(A)=\sum_{n}\nu_n(A)=\sum_{n}\int_A f_{n}\,\mathrm{d}\mu_{n}=\sum_{n}\int_A f_n \dsone_{A_{n}}\,\mathrm{d}\mu=\int_A \sum_{n}f_{n}\dsone_{A_{n}}\,\mathrm{d}\mu.$$

*Step 2.* Construct the candidate for the Radon-Nikodým derivative.
Defining
$$\mathcal{C}:=\{g\text{ Borel function}:{\textstyle \int_{A}g\mathrm{d}\mu}\leqslant\nu(A)\,\,\forall A\in\mathcal{F}\},$$
the candidate is a Borel function $f\in\mathcal{C}$ satisfying
$$\int_\Omega f\,\mathrm{d}\mu\geqslant\int_\Omega g\mathrm{d}\mu\,\,\forall g\in\mathcal{C}.$$

First note that for $g_{1},g_{2}\in\mathcal{C}$,
$g:=\max\{g_{1},g_{2}\}\in\mathcal{C}$. Indeed,
$\int_{A}g\,\mathrm{d}\mu=\int_{A\cap\{g_{1}\leqslant g_{2}\}}g_{2}\,\mathrm{d}\mu+\int_{A\cap\{g_{1}>g_{2}\}}g_{1}\,\mathrm{d}\mu\leqslant\mu(A\cap\{g_{1}\leqslant g_{2}\}+\mu(A\cap\{g_{1}>g_{2}\}=\mu(A)$.

Now take $(g_{n})_{n}$ in $\mathcal{C}$ such that
$\int_{\Omega}g_{n}\mathrm{d}\mu\uparrow\alpha:=\sup\{{\textstyle \int_{\Omega}g\mathrm{d}\mu}:g\in\mathcal{C}\}\leqslant\nu(A)<\infty$,
and define $f_{n}:=\max\{g_{1},\dots,g_{n}\}\in\mathcal{C}$.

Define $f:=\lim_{n}f_{n}$. By Monotone Convergence Theorem,
$\int_\Omega f\,\mathrm{d}\mu=\alpha$ and
$\int_{A}f\,\mathrm{d}\mu=\lim_{n}\int_{A}f_{n}\,\mathrm{d}\mu\leqslant\nu(A)$,
so $f\in\mathcal{C}$. In particular, $f$ is finite a.e., and by changing
$f$ on a null set, we get a function with the desired properties.

*Step 3.* Check that $f$ is the Radon-Nikodým derivative. Consider the
measure $$\nu_{0}(A):=\nu(A)-\int_{A}f\,\mathrm{d}\mu$$ and show that
$\nu_{0}(\Omega)=0$.

Let $\varepsilon>0$. We are going to show that
$$\nu_{\varepsilon}:=\varepsilon\mu-\nu_{0}$$ is non-negative, whence
$\nu_{0}(\Omega)=\varepsilon\mu(\Omega)-\nu_{\varepsilon}(\Omega)\leqslant\varepsilon\mu(\Omega)$
and, since $\varepsilon$ is arbitrary, $\nu_{0}(\Omega)=0$, this will
conclude the proof.

By the Hahn Decomposition Theorem, there is a set $N$ such that
$\nu_{\varepsilon}(A\cap N)\leqslant 0$ and
$\nu_{\varepsilon}(A\cap N^{c})\geqslant 0$ for every $A\in\mathcal{F}$.
Taking $$\nonumber
g=f+\varepsilon\dsone_{N},$$ one can readily check that
$g\in\mathcal{C}$. Indeed,
$\int_{A}g\,\mathrm{d}\mu=\int_{A}f\,\mathrm{d}\mu+\varepsilon\mu(A\cap N)=\int_{A}f\,\mathrm{d}\mu+\nu_{\varepsilon}(A\cap N)+\nu_{0}(A)=\int_{A}f\,\mathrm{d}\mu+\nu_{\varepsilon}(A\cap N)+\nu(A)-\int_{A}f\,\mathrm{d}\mu\leqslant\nu(A)$.

On the other hand, by maximality of $f$, we have
$\int_\Omega f\,\mathrm{d}\mu\geqslant\int_\Omega g\,\mathrm{d}\mu=\int_\Omega f\,\mathrm{d}\mu+\varepsilon\mu(N)$,
hence $\mu(N)=0$. Since $\nu$ is absolutely continuous with respect to
$\mu$, we have $\nu(N)=0$. Therefore, $\nu_{\varepsilon}(N)=0$ and
$\nu_{\varepsilon}(A)\geqslant 0$ for all $A\in\mathcal{F}$. As
discussed above, this completes the proof.[^24]
:::

We finally give the postponed proofs from \@ref(sec:prodfubi).

:::{.proof name="Proof of Example \@ref(exm:2dimborel)"}
First, we show
$\mathcal{B}(\mathbb{R}^2) \subseteq \mathcal{B}(\mathbb{R}) \otimes \mathcal{B}(\mathbb{R})$.
Let
$$\mathcal{E} := \{(a,b] \cap \mathbb{R}: -\infty \leqslant a \leqslant b \leqslant+\infty\}
,$$ $\mathcal{E}^2 := \mathcal{E}\times \mathcal{E}$, and recall that
$\mathcal{B}(\mathbb{R}^2) = \sigma(\mathcal{E}^2)$. Since
$\mathcal{E}^2 \subseteq \mathcal{B}(\mathbb{R}) \times \mathcal{B}(\mathbb{R})$,
we have
$\mathcal{B}(\mathbb{R}^2) \subseteq \sigma(\mathcal{B}(\mathbb{R}) \times \mathcal{B}(\mathbb{R})) = \mathcal{B}(\mathbb{R}) \otimes\mathcal{B}(\mathbb{R})$.

We now show the other direction. Note that
$$\{ A \times B : A \in \sigma(\mathcal{E}), B=\mathbb{R}\}
=
\sigma( \{ A \times B : A \in \mathcal{E}, B=\mathbb{R}\} )$$ as the set
$B$ is being pinned to $B=\mathbb{R}$ plays no role in any of the
theoretic operations involved. Likewise,
$$\{ A \times B : A=\mathbb{R}, B \in \sigma(\mathcal{E}) \}
=
\sigma( \{ A \times B : A = \mathbb{R}, B \in \mathcal{E}\} )
.$$ In particular, for
$A,B \in \mathcal{B}(\mathbb{R}) = \sigma(\mathcal{E})$, we have
$$A \times B = (A \times \mathbb{R}) \cap (\mathbb{R}\times B) \in \sigma( \mathcal{E}\times \mathcal{E}).$$
Thus,
$\sigma(\mathcal{E}) \times \sigma(\mathcal{E}) \subseteq \sigma(\mathcal{E}\times \mathcal{E})$
and hence $$\nonumber
\mathcal{B}(\mathbb{R}) \times \mathcal{B}(\mathbb{R}) = \sigma(\mathcal{E}) \times \sigma(\mathcal{E}) \subseteq \sigma(\mathcal{E}\times \mathcal{E}) = \sigma(\mathcal{E}^2) = \mathcal{B}(\mathbb{R}^2),$$
Therefore,
$\mathcal{B}(\mathbb{R}) \otimes\mathcal{B}(\mathbb{R}) = \sigma(\mathcal{B}(\mathbb{R}) \times \mathcal{B}(\mathbb{R})) \subseteq \mathcal{B}(\mathbb{R}^2)$.
:::

:::{.proof name="Proof of Lemma \@ref(lem:sectionprop)"}
For the first statement, we show that each section $E_x$ is
$\mathcal{F}_2$-measurable. A symmetric reasoning can be used to show
that each section $E^y$ is $\mathcal{F}_1$-measurable. Fix
$x \in \Omega_1$, and define the collection $\mathcal{G}$ by
$$\mathcal{G}= \{E \subseteq \Omega_1 \times \Omega_2 : E_x \in \mathcal{F}_2\}.$$
By construction, $\mathcal{G}$ contains
$\mathcal{F}_1 \times \mathcal{F}_2$. It remains to show that
$\mathcal{G}$ is a $\sigma$-algebra on $\Omega_1 \times \Omega_2$, so
that it contains
$\sigma(\mathcal{F}_1 \times \mathcal{F}_2) = \mathcal{F}_1 \otimes\mathcal{F}_2$.
Indeed, we have

(i) $\Omega_1 \times \Omega_2 \in \mathcal{G}$, since
    $(\Omega_1 \times \Omega_2)_x = \Omega_2 \in \mathcal{F}_2$.

(ii) Let $E \in \mathcal{G}$. Since $E_x \in \mathcal{F}_2$, then
     $(E^c)_x = (E_x)^c \in \mathcal{F}_2$, so that
     $E^c \in \mathcal{G}$.

(iii) Let $E_1, E_2, \dots \in \mathcal{G}$. Then,
      $(E_j)_x \in \mathcal{F}_2$ for each $j \in \mathbb{N}$. This in
      turn gives
      $$\Big( \bigcup_{i=1}^{\infty}E_i \Big)_x = \bigcup_{i=1}^{\infty}(E_i)_x \in \mathcal{F}_2,$$
      so that $\bigcup_{i=1}^{\infty}E_i \in \mathcal{G}$.

where we use the identities $(E^c)_x = (E_x)^c$ and
$(\bigcup_{i=1}^{\infty}E_i)_x = \bigcup_{i=1}^{\infty}(E_i)_x$.

We now prove the second statement. Again, we only prove that each $f_x$
is $\mathcal{F}_2$-measurable. Note that $(f_x)^{-1}(D) = (f^{-1}(D))_x$
for any $D \in \mathcal{B}(\mathbb{R})$. Combined with the first
statement, this implies that $(f_x)^{-1}(D) \in \mathcal{F}_2$ for every
$D \in \mathcal{B}$, concluding the proof.[^25]
:::

:::{.proof name="Proof of Lemma \@ref(lem:measurefn)"}
We show that $x \mapsto \nu(E_x)$ is
$\mathcal{F}_1$-measurable, the other statement is analogous.

First, suppose that the measure $\nu$ is finite. Define the collection
$\mathcal{G}$ by
$$\mathcal{G}= \{E \in \mathcal{F}_1 \otimes\mathcal{F}_2 : x \mapsto \nu(E_x) \ \text{is $\mathcal{F}_1$-measurable}\}.$$
We will show that $\mathcal{G}= \mathcal{F}_1 \otimes\mathcal{F}_2$.

Note from Lemma \@ref(lem:sectionprop) (i) that, given
$E \in \mathcal{F}_1 \otimes\mathcal{F}_2$, each section $E_x$ lies in
$\mathcal{F}_2$, so that the function $x \mapsto \nu(E_x)$ is
well-defined. If $A \in \mathcal{F}_1$ and $B \in \mathcal{F}_2$, we
have 
\begin{equation}
(\#eq:prodaux)
\nu((A \times B)_x) = \nu(B) \dsone_A(x)
\end{equation}
which implies that
$\mathcal{G}$ contains $\mathcal{F}_1 \times \mathcal{F}_2$. Note that
$\mathcal{F}_1 \times \mathcal{F}_2$ defines a $\pi$-system on
$\Omega_1 \times \Omega_2$. We now show that $\mathcal{G}$ is a
$\lambda$-system. Indeed, we have

(i) $\Omega_1 \times \Omega_2 \in \mathcal{G}$.

(ii) For $E \in \mathcal{G}$, we can write
     $$\nu((E^c)_x) = \nu((E_x)^c) = \nu(\Omega_2) - \nu(E_x),$$ and so
     $E^c \in \mathcal{G}$.

(iii) Let $E_1, E_2, \dots \in \mathcal{G}$, where
      $E_i \cap E_j = \emptyset$ for $i \neq j$. Then, by countable
      additivity of $\nu$, we get
      $$\nu\Big(\Big(\bigcup_{i=1}^{\infty}E_i\Big)_x\Big) = \nu\Big(\bigcup_{i=1}^{\infty}(E_i)_x\Big) = \sum_{i=1}^{\infty}\nu((E_i)_x),$$
      so that $\bigcup_{i=1}^{\infty}E_i \in \mathcal{G}$.

Therefore, the $\pi$-$\lambda$ Theorem gives
$\mathcal{F}_1 \otimes\mathcal{F}_2 = \sigma( \mathcal{F}_1 \times \mathcal{F}_2 ) \subseteq \mathcal{G}\subseteq \mathcal{F}_1 \otimes\mathcal{F}_2$,
concluding the proof.

Now, suppose that $\nu$ is $\sigma$-finite, and let
$\{D_i\}_{i=1}^{\infty}$ be a sequence of disjoint events in
$\mathcal{F}_2$ with $\nu(D_j) < \infty, \ \forall j \in N$, and
$\bigcup_{i=1}^{\infty}D_i = \Omega_2$. Define the finite measures
$\nu_1, \nu_2, \dots$ by
$$\nu_k(B) = \nu(B \cap D_k), \ k \in \mathbb{N}.$$ Given
$E \in \mathcal{F}_1 \otimes\mathcal{F}_2$, each $x \mapsto \nu_k(E_x)$
is $\mathcal{F}_1$-measurable, hence
$$\nu(E_x) = \sum_{i=1}^{\infty}\nu(B \cap D_i) = \sum_{i=1}^{\infty}\nu_i(E_x),$$
is also $\mathcal{F}_1$-measurable. Arguing similarly for the function
$y \mapsto \mu(E^y)$ finishes the proof.[^26]
:::

:::{.proof name="Proof of Theorem \@ref(thm:prodmeasure)"}
We start with uniqueness of the measure $\mu \otimes\nu$. Since
$\mathcal{F}_1 \times \mathcal{F}_2$ is a $\pi$-system that generates
$\mathcal{F}_1 \otimes\mathcal{F}_2$, we can apply the
$\pi$-$\lambda$ Theorem to get uniqueness. Moreover, to get existence as
well as the second formula, it is enough to show that each of those two
integrals yield a measure which satisfies the first one.

We know from Lemma \@ref(lem:measurefn) that, given
$E \in \mathcal{F}_1 \otimes\mathcal{F}_2$, the functions
$x \mapsto \nu(E_x)$ and $y \mapsto \mu(E^y)$ are
$\mathcal{F}_1$-measurable and $\mathcal{F}_2$-measurable, respectively.

So we can define the set functions
$(\mu \otimes\nu)_1: \mathcal{F}_1 \otimes\mathcal{F}_2 \to [0,\infty]$
and
$(\mu \otimes\nu)_2: \mathcal{F}_1 \otimes\mathcal{F}_2 \to [0,\infty]$
by
$$(\mu \otimes\nu)_1(E) = \int_{\Omega_1} \nu(E_x) \mu(\mathrm{d}x) \quad \text{and} \quad (\mu \otimes\nu)_2(E) = \int_{\Omega_2} \mu(E^y) \nu(\mathrm{d}y).$$

Let us check that $(\mu \otimes\nu)_1$ is a measure:

(i) $(\mu \otimes\nu)_1(\emptyset) = \int_{\Omega_1} \nu(\emptyset) \mu(\mathrm{d}x) = 0$.

(ii) Let $E_1, E_2 , \dots \in \mathcal{F}_1 \otimes\mathcal{F}_2$,
     where $E_i \cap E_j = \emptyset$ for $i \neq j$. By countable
     additivity of $\nu$, we have $$\begin{gathered}
     (\mu \otimes\nu)_1(\bigcup_{i=1}^{\infty}E_i)
     = \int_{\Omega_1} \nu((\bigcup_{i=1}^{\infty}E_i)_x) \mu(\mathrm{d}x)
     = \int_{\Omega_1} \nu( \bigcup_{i=1}^{\infty} (E_i )_x) \mu(\mathrm{d}x)
     =
     \\
     = \sum_{i=1}^{\infty} \int_{\Omega_1} \nu((E_i)_x) \mu(\mathrm{d}x)
     = \sum_{i=1}^{\infty} (\mu \otimes\nu)_1(E_i).\end{gathered}$$

By analogous argument, $(\mu \otimes\nu)_2$ is also a measure.

Moreover, for every $A \times B \in \mathcal{F}_1 \times \mathcal{F}_2$,
by \@ref(eq:prodaux) we have
$$(\mu \otimes\nu)_1(A \times B) = \mu(A) \nu(B)
,$$ and analogously we can prove
$(\mu \otimes\nu)_2 (A \times B) = \mu(A) \nu(B)$. As noted in the first
paragraph, this concludes the proof.[^27]
:::

[^1]: See [](\detokenize{https://youtu.be/s86-Z-CbaHA}) for a nice
    overview of the proof.

[^2]: See [@Cohn13 1.4.9] for a complete proof.

[^3]: Note that $(a,b]=\emptyset$ when $b\leqslant a$, so
    $\emptyset\in\mathcal{C}$ and $\mathcal{C}$ is closed under
    intersections.

[^4]: Expanded from [@Cohn13 1.6.4].

[^5]: This requires the Hahn-Banach Theorem which is a topic of
    Functional Analysis.

[^6]: Example from [@Bartle95].

[^7]: Based on [@Shiryaev16 §2.6.7].

[^8]: Let us prove that it is not Riemann integrable. Consider any
    partition of $[0,1]$ into finitely many non-degenerate intervals,
    and notice that all intervals will contain both rational and
    irrational numbers. Thus, every step function $g \leqslant f$ must
    satisfy $g \leqslant 0$ a.e., and every step function
    $h \geqslant f$ must satisfy $h \geqslant 1$ a.e. Hence,
    $\int g \,\mathrm{d}x \leqslant 0$ and
    $\int h \,\mathrm{d}x \geqslant 1$ and taking
    $\varepsilon=\frac{1}{3}$ we see that there is no number $L$ such
    that
    $L - \varepsilon < \int g \,\mathrm{d}x \leqslant\int h \,\mathrm{d}x < L + \varepsilon$.

[^9]: Note that this is false without assuming that $\mu$ is
    $\sigma$-finite: taking $\Omega=\{1\}$ and $\mu(\{1\})=\infty$, any
    positive $f$ will yield $\nu=\mu$.

[^10]: $f_X(x)=x^{-1}\dsone_{[1,e]}(x)$

[^11]: Expanded from [@Cohn13 5.1.5].

[^12]: Based on [@Cohn13 5.2.1].

[^13]: Based on [@Cohn13 5.2.2].

[^14]: Based on [@Cohn13 5.3.1].

[^15]: Expanded from [@Cohn13 5.3.2].

[^16]: Expanded from [@Cohn13 5.3.2].

[^17]: A more laborious approach without using product measures would be
    to start from the non-negative case, take independent simple
    approximations, expand the expression for integral, use MCT, and
    finally bootstrap to the integrable case.

[^18]: This is defined in the same way the smallest $\sigma$-algebra
    that contains a given class.

[^19]: Based on [almostsuremath.com](https://almostsuremath.com/2019/10/06/the-monotone-class-theorem/)

[^20]: Adapted from [@Kub15 Proposition 8.3].

[^21]: Adapted from [@Kub15 Theorem 8.4].

[^22]: Adapted from [@Dem20 Lemma 1.1.31].

[^23]: Adapted from Wikipedia.

[^24]: Adapted from Wikipedia.

[^25]: Based on [@Cohn13 5.1.2].

[^26]: Expanded from [@Cohn13 5.1.3].

[^27]: Expanded from [@Cohn13 5.1.4].
